/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab8.gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import lab8.Helper;
import lab8.logic.JournalRecordsController;

/**
 *
 *
 */
public class NewRecordDialog extends javax.swing.JDialog {
    private final JournalRecordsController controller;
    /**
     * Creates new form NewRecordDialog
     */
    public NewRecordDialog(java.awt.Frame parent, boolean modal, JournalRecordsController controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        this.dateField.setText(Helper.DATE_FORMAT.format(new Date()));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productLabel = new javax.swing.JLabel();
        productField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        countField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JFormattedTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        productLabel.setText("Product:");

        jLabel1.setText("Count:");

        countField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel2.setText("Date:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productLabel)
                    .addComponent(productField)
                    .addComponent(jLabel1)
                    .addComponent(countField)
                    .addComponent(jLabel2)
                    .addComponent(dateField)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            String productString = this.productField.getText();
            String dateString = this.dateField.getText();
            String countString = this.countField.getText();
            for(String str : new String[]{productString, dateString, countString}){
                if(str.equals("")){
                    this.showErrorMsg();
                    return;
                }
            }
            Date date = Helper.DATE_FORMAT.parse(dateString);
            int count = Integer.parseInt(countString);
            this.controller.addRecord(productString, count, date);
            this.dispose();
        } 
        catch (ParseException | NumberFormatException ex) {
            this.showErrorMsg();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void showErrorMsg(){
        JOptionPane.showMessageDialog(this, "Some of fields doesn't filled rigth.\n"
                + "Note that all field should be setted, count field\n"
                + "should contain integer number & date must be in format"
                + "dd/MM/yyyy!","Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JFormattedTextField countField;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField productField;
    private javax.swing.JLabel productLabel;
    // End of variables declaration//GEN-END:variables
}
